{"name": "Проверка невозможности авторизации курьера под несуществующим пользователем", "status": "passed", "description": "Проверяем, что при попытке авторизации несуществуего курьеравозвращается ошибка с кодом ответа 404, и текстом \"Учетная запись не найдена\"", "steps": [{"name": "Генерация login, password и first_name курьера", "status": "passed", "start": 1705859709730, "stop": 1705859709730}, {"name": "Авторизация курьера", "status": "passed", "parameters": [{"name": "login_pass", "value": "['jkinnlzybh', 'ttsjtswhbe']"}], "start": 1705859709730, "stop": 1705859709800}], "start": 1705859709730, "stop": 1705859709800, "uuid": "c7d65f40-edd2-40e1-a44f-081767b8b400", "historyId": "4a051b3addde4d8adb41e5163aa3608a", "testCaseId": "4a051b3addde4d8adb41e5163aa3608a", "fullName": "tests.test_login_courier#test_login_with_nonexistent_courier", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "host", "value": "HOME-PC"}, {"name": "thread", "value": "36652-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}